---
# Example ScenarioDefinition - Basic OAuth2
apiVersion: devopsbeerer.io/v1alpha1
kind: ScenarioDefinition
metadata:
  name: scenario-1
spec:
  name: "Scenario 1"
  id: "scenario-1"
  description: "A simple scenario with a SPA and an API"
  tags: ["oauth2", "authorization-code", "crud", "api", "keycloak"]
  features:
    - "OAuth2 Authorization Code Flow"
    - "Access Token Management"
    - "Basic CRUD Operations"
    - "Role-based Access (User/Admin)"
    - "RESTful API"
  helmChart:
    link: "https://github.com/DevOpsBeerer/playground-scenarios-charts.git"
    dir: "scenario-1"
