---
# CRD for Scenario Catalog - Defines available scenarios
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scenariodefinitions.devopsbeerer.io
spec:
  group: devopsbeerer.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
                - id
                - description
                - helmChart
              properties:
                name:
                  type: string
                  description: "Human-readable name of the scenario"
                  example: "Basic OAuth2 Beer Management"
                id:
                  type: string
                  description: "Unique identifier with hyphens"
                  pattern: "^[a-z0-9]+(-[a-z0-9]+)*$"
                  example: "basic-oauth2-beer-mgmt"
                description:
                  type: string
                  description: "Detailed description of the scenario"
                helmChart:
                  type: object
                  required:
                    - link
                  properties:
                    link:
                      type: string
                      description: "Git repository URL for helm charts"
                      pattern: "^https://.*\\.git$"
                      default: "https://github.com/DevOpsBeerer/playground-scenarios-charts.git"
                    dir:
                      type: string
                      description: "Subdirectory containing the helm chart (optional, defaults to scenario ID)"
                tags:
                  type: array
                  description: "Tags for categorizing scenarios"
                  items:
                    type: string
                  example: ["oauth2", "basic", "api", "crud"]
                features:
                  type: array
                  description: "List of features demonstrated in this scenario"
                  items:
                    type: string
                  example:
                    [
                      "authorization-code-flow",
                      "refresh-tokens",
                      "rbac",
                      "api-gateway",
                    ]
      additionalPrinterColumns:
        - name: Name
          type: string
          jsonPath: .spec.name
        - name: ID
          type: string
          jsonPath: .spec.id
        - name: Tags
          type: string
          jsonPath: .spec.tags
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Cluster
  names:
    plural: scenariodefinitions
    singular: scenariodefinition
    kind: ScenarioDefinition
    shortNames:
      - scndef
      - sd

---
# CRD for Active Scenario - Manages currently played scenario
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: activescenarios.devopsbeerer.io
spec:
  group: devopsbeerer.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - scenarioId
              properties:
                scenarioId:
                  type: string
                  description: "ID of the scenario definition to deploy"
                  pattern: "^[a-z0-9]+(-[a-z0-9]+)*$"
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "Current phase of the scenario deployment"
                  enum:
                    - Pending
                    - Deploying
                    - Running
                    - Failed
                    - Terminating
                scenarioName:
                  type: string
                  description: "Name of the deployed scenario"
                message:
                  type: string
                  description: "Human-readable message about the current status"
                lastTransitionTime:
                  type: string
                  format: date-time
                  description: "Last time the status changed"
                helmReleaseName:
                  type: string
                  description: "Name of the Helm release"
                startTime:
                  type: string
                  format: date-time
                  description: "When the scenario was started"
      additionalPrinterColumns:
        - name: Scenario
          type: string
          jsonPath: .spec.scenarioId
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Helm Release
          type: string
          jsonPath: .status.helmReleaseName
        - name: Started
          type: date
          jsonPath: .status.startTime
  scope: Cluster
  names:
    plural: activescenarios
    singular: activescenario
    kind: ActiveScenario
    shortNames:
      - as
      - active
