apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "devopsbeerer-operator.fullname" . }}-role
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
rules:
- apiGroups: ["devopsbeerer.ch"]
  resources: ["activescenarios"]
  verbs: ["watch", "get", "list", "update", "patch"]
- apiGroups: ["devopsbeerer.ch"]
  resources: ["scenariodefinitions"]
  verbs: ["get", "list"]
- apiGroups: ["devopsbeerer.ch"]
  resources: ["scenariohistories"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "devopsbeerer-operator.fullname" . }}-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "devopsbeerer-operator.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "devopsbeerer-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
